### ISSUE TITLE
F2.1 - Send pageviews to analytics services [5pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#275]
[Feature](https://github.com/orgs/frontity/projects/2#card-31921663)

**Tasks**
- [ ] Implement API for sendPageview.
- [ ] Implement API for afterCSR.
- [ ] Tests:
  - [ ] sendPageview.
  - [ ] afterCSR.
  - [ ] It works with different services.
  - [ ] You can send data to just one service.
- [ ] Docs.

Branch: `analytics`
Pull Request: #267
