### ISSUE TITLE
F2.2 Send events to analytics services [3pt]

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#276]
[Feature](https://github.com/orgs/frontity/projects/2#card-31921663)

**Tasks**
- [ ] Implement API for sendEvent.
- [ ] Tests:
  - [ ] sendEvent.
  - [ ] It works with different services.
  - [ ] You can send data to just one service.
- [ ] Docs.

Branch: `analytics`
Pull Request: #267
