### ISSUE TITLE
F2.3 Send specific data to just one of my analytics services

### ISSUE THREAD

**Issue by SantosGuillamot** [frontity/frontity#277]
[Feature](https://github.com/orgs/frontity/projects/2#card-31921663)

**Tasks**
- [ ] Implement for sendPageview.
- [ ] Implement for sendEvent.
- [ ] Tests:
  - [ ] sendPageview
  - [ ] sendEvent.
  - [ ] It works with different services.
- [ ] Docs.

Branch: `analytics`
Pull Request: #267
